packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  diff@<4.0.4: '>=4.0.4'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  tmp@<=0.2.3: '>=0.2.4'
