apiVersion: v1
kind: ConfigMap
metadata:
  name: clean-dev-pg-monitoring
data:
  custom-queries.yaml: |
    # Simplified monitoring queries for single-instance PostgreSQL

    # Database size
    database_size:
      query: |
        SELECT
          datname,
          pg_database_size(datname) as size_bytes
        FROM pg_database
        WHERE datname = 'cleandev'
      metrics:
        - datname:
            usage: "LABEL"
            description: "Database name"
        - size_bytes:
            usage: "GAUGE"
            description: "Database size in bytes"

    # Connection stats
    connection_stats:
      query: |
        SELECT
          datname,
          state,
          COUNT(*) as connections
        FROM pg_stat_activity
        WHERE datname = 'cleandev'
        GROUP BY datname, state
      metrics:
        - datname:
            usage: "LABEL"
            description: "Database name"
        - state:
            usage: "LABEL"
            description: "Connection state"
        - connections:
            usage: "GAUGE"
            description: "Number of connections"

    # Cache hit ratio
    cache_hit_ratio:
      query: |
        SELECT
          'cleandev' as datname,
          CASE
            WHEN blks_hit + blks_read = 0 THEN 1
            ELSE round(blks_hit::numeric / (blks_hit + blks_read)::numeric, 4)
          END as ratio
        FROM pg_stat_database
        WHERE datname = 'cleandev'
      metrics:
        - datname:
            usage: "LABEL"
            description: "Database name"
        - ratio:
            usage: "GAUGE"
            description: "Cache hit ratio (0-1)"

    # Transaction stats
    transaction_stats:
      query: |
        SELECT
          'cleandev' as datname,
          xact_commit,
          xact_rollback,
          deadlocks
        FROM pg_stat_database
        WHERE datname = 'cleandev'
      metrics:
        - datname:
            usage: "LABEL"
            description: "Database name"
        - xact_commit:
            usage: "COUNTER"
            description: "Transactions committed"
        - xact_rollback:
            usage: "COUNTER"
            description: "Transactions rolled back"
        - deadlocks:
            usage: "COUNTER"
            description: "Deadlocks detected"
