apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: clean-dev-pg-pooler
spec:
  cluster:
    name: clean-dev-pg

  instances: 1  # Single pooler for single PostgreSQL instance
  type: rw

  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "200"  # Reduced for small blog
      default_pool_size: "10"  # Fewer connections per pool
      max_db_connections: "50"  # Match reduced PostgreSQL max_connections
      max_user_connections: "50"
      reserve_pool_size: "5"
      reserve_pool_timeout: "5"
      log_connections: "1"
      log_disconnections: "1"
      log_pooler_errors: "1"
      stats_period: "60"

  # Resources for pooler
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

  # Monitoring
  monitoring:
    enablePodMonitor: true

  template:
    metadata:
      labels:
        app: clean-dev-pg-pooler
    spec:
      containers: []
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: cnpg.io/cluster
                      operator: In
                      values:
                        - clean-dev-pg
                topologyKey: kubernetes.io/hostname
